create table if not exists medicaments (
  id bigint generated by default as identity primary key,
  nom text not null,
  dose text not null,
  heure text not null,
  photo_url text,
  quantite_restante integer not null default 0,
  seuil_alerte integer not null default 2,
  proche_nom text,
  proche_contact text,
  created_at timestamptz not null default now()
);

create index if not exists medicaments_created_at_idx on medicaments (created_at desc);

create table if not exists prises (
  id bigint generated by default as identity primary key,
  medicament_id bigint not null references medicaments(id) on delete cascade,
  statut text not null default 'prise_confirmee',
  commentaire text,
  taken_at timestamptz not null default now()
);

create index if not exists prises_taken_at_idx on prises (taken_at desc);
create index if not exists prises_medicament_id_idx on prises (medicament_id);

create table if not exists rappels_partages (
  id bigint generated by default as identity primary key,
  medicament_id bigint not null references medicaments(id) on delete cascade,
  destinataire text not null,
  message text not null,
  sent_at timestamptz not null default now()
);

create index if not exists rappels_partages_sent_at_idx on rappels_partages (sent_at desc);

create table if not exists rendez_vous (
  id bigint generated by default as identity primary key,
  titre text not null,
  medecin text not null,
  date_heure timestamptz not null,
  lieu text,
  notes text,
  rappel_minutes integer not null default 60,
  created_at timestamptz not null default now()
);

create index if not exists rendez_vous_date_heure_idx on rendez_vous (date_heure asc);
